//! Unit templates and card definitions
//!
//! This module contains all unit card templates used in the game.

use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;

use crate::types::{Ability, AbilityCondition, AbilityEffect, AbilityTarget, AbilityTrigger};

/// Card template for creating starter deck cards
pub struct CardTemplate {
    pub template_id: &'static str,
    pub name: &'static str,
    pub attack: i32,
    pub health: i32,
    pub play_cost: i32,
    pub pitch_value: i32,
    pub abilities: Vec<Ability>,
    pub is_token: bool,
}

/// The comprehensive "First Pack" of units
pub fn get_starter_templates() -> Vec<CardTemplate> {
    vec![
        // ==========================================
        // TIER 1 (COST 1-2): Early Game / Tokens
        // ==========================================
        CardTemplate {
            template_id: "rat_swarm",
            name: "Rat Swarm",
            attack: 1,
            health: 1,
            play_cost: 1,
            pitch_value: 1,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnFaint,
                effect: AbilityEffect::SpawnUnit {
                    template_id: String::from("rat_token"),
                },
                name: String::from("Infestation"),
                description: String::from("Spawn a Rat Token when killed"),
                condition: AbilityCondition::None,
                max_triggers: Some(1),
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "goblin_scout",
            name: "Goblin Scout",
            attack: 1,
            health: 2,
            play_cost: 1,
            pitch_value: 2,
            abilities: vec![],
            is_token: false,
        },
        CardTemplate {
            template_id: "goblin_grunt",
            name: "Goblin Grunt",
            attack: 2,
            health: 2,
            play_cost: 2,
            pitch_value: 1,
            abilities: vec![],
            is_token: false,
        },
        CardTemplate {
            template_id: "scaredy_cat",
            name: "Scaredy Cat",
            attack: 1,
            health: 3,
            play_cost: 1,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::ModifyStats {
                    health: 2,
                    attack: 0,
                    target: AbilityTarget::BackAlly,
                },
                name: String::from("Hiss"),
                description: String::from("Give the ally behind +2 Health at start"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "militia",
            name: "Militia",
            attack: 2,
            health: 2,
            play_cost: 2,
            pitch_value: 2,
            abilities: vec![],
            is_token: false,
        },
        CardTemplate {
            template_id: "shield_bearer",
            name: "Shield Bearer",
            attack: 1,
            health: 4,
            play_cost: 2,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::ModifyStats {
                    health: 2,
                    attack: 0,
                    target: AbilityTarget::FrontAlly,
                },
                name: String::from("Shield Wall"),
                description: String::from("Heal front ally for 2 at start"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "nurse_goblin",
            name: "Nurse Goblin",
            attack: 1,
            health: 3,
            play_cost: 2,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::BeforeAnyAttack,
                effect: AbilityEffect::ModifyStats {
                    health: 2,
                    attack: 0,
                    target: AbilityTarget::FrontAlly,
                },
                name: String::from("Emergency Heal"),
                description: String::from("Heal front ally for 2 if its health is <= 6"),
                condition: AbilityCondition::TargetHealthLessThanOrEqual { value: 6 },
                max_triggers: None,
            }],
            is_token: false,
        },

        // ==========================================
        // TIER 2 (COST 3-4): Mid Game Synergies
        // ==========================================
        CardTemplate {
            template_id: "wolf_rider",
            name: "Wolf Rider",
            attack: 3,
            health: 2,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnFaint,
                effect: AbilityEffect::Damage {
                    amount: 2,
                    target: AbilityTarget::FrontEnemy,
                },
                name: String::from("Dying Bite"),
                description: String::from("Deal 2 damage to front enemy on death"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "archer",
            name: "Archer",
            attack: 1,
            health: 3,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::Damage {
                    amount: 1,
                    target: AbilityTarget::BackEnemy,
                },
                name: String::from("Long Shot"),
                description: String::from("Deal 1 damage to the back enemy at start"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "skeleton_archer",
            name: "Skeleton Archer",
            attack: 2,
            health: 2,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::Damage {
                    amount: 2,
                    target: AbilityTarget::RandomEnemy,
                },
                name: String::from("Bone Arrow"),
                description: String::from("Deal 2 damage to a random enemy at start"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "battle_hardened",
            name: "Battle Hardened",
            attack: 2,
            health: 3,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![
                Ability {
                    trigger: AbilityTrigger::BeforeUnitAttack,
                    effect: AbilityEffect::ModifyStats {
                        health: 2,
                        attack: 0,
                        target: AbilityTarget::SelfUnit,
                    },
                    name: String::from("Brace"),
                    description: String::from("Gain +2 health before attacking"),
                    condition: AbilityCondition::None,
                    max_triggers: None,
                },
                Ability {
                    trigger: AbilityTrigger::AfterUnitAttack,
                    effect: AbilityEffect::ModifyStats {
                        health: 0,
                        attack: 2,
                        target: AbilityTarget::SelfUnit,
                    },
                    name: String::from("Adrenaline"),
                    description: String::from("Gain +2 attack after attacking"),
                    condition: AbilityCondition::None,
                    max_triggers: None,
                },
            ],
            is_token: false,
        },
        CardTemplate {
            template_id: "lone_wolf",
            name: "Lone Wolf",
            attack: 2,
            health: 4,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::BeforeUnitAttack,
                effect: AbilityEffect::ModifyStats {
                    health: 0,
                    attack: 5,
                    target: AbilityTarget::SelfUnit,
                },
                name: String::from("Last Stand"),
                description: String::from("Gain +5 attack if you are the only ally"),
                condition: AbilityCondition::AllyCountAtMost { count: 1 },
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "pack_leader",
            name: "Pack Leader",
            attack: 2,
            health: 3,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::ModifyStats {
                    health: 1,
                    attack: 1,
                    target: AbilityTarget::AllAllies,
                },
                name: String::from("Strength in Numbers"),
                description: String::from("Give all allies +1/+1 if you have 3+ allies"),
                condition: AbilityCondition::AllyCountAtLeast { count: 3 },
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "vampire",
            name: "Vampire",
            attack: 3,
            health: 3,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::AfterUnitAttack,
                effect: AbilityEffect::ModifyStats {
                    health: 2,
                    attack: 0,
                    target: AbilityTarget::SelfUnit,
                },
                name: String::from("Lifesteal"),
                description: String::from("Heal 2 health after attacking"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "raging_orc",
            name: "Raging Orc",
            attack: 2,
            health: 8,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnDamageTaken,
                effect: AbilityEffect::ModifyStats {
                    health: 0,
                    attack: 2,
                    target: AbilityTarget::SelfUnit,
                },
                name: String::from("Berserk"),
                description: String::from("Gain +2 attack when hurt"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "zombie_captain",
            name: "Zombie Captain",
            attack: 3,
            health: 4,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnFaint,
                effect: AbilityEffect::SpawnUnit {
                    template_id: String::from("zombie_soldier"),
                },
                name: String::from("Undead Call"),
                description: String::from("Spawn a Zombie Soldier on death"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "necromancer",
            name: "Necromancer",
            attack: 2,
            health: 3,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnSpawn,
                effect: AbilityEffect::ModifyStats {
                    health: 0,
                    attack: 2,
                    target: AbilityTarget::SelfUnit,
                },
                name: String::from("Spawn Boost"),
                description: String::from("Give +2 attack to any spawned unit"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "headhunter",
            name: "Headhunter",
            attack: 4,
            health: 2,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::Damage {
                    amount: 5,
                    target: AbilityTarget::LowestHealthEnemy,
                },
                name: String::from("Assassinate"),
                description: String::from("Deal 5 damage to the enemy with the lowest health"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "giant_slayer",
            name: "Giant Slayer",
            attack: 2,
            health: 2,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::Damage {
                    amount: 3,
                    target: AbilityTarget::HighestAttackEnemy,
                },
                name: String::from("Weak Point"),
                description: String::from("Deal 3 damage to the enemy with the highest attack"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "shield_squire",
            name: "Shield Squire",
            attack: 2,
            health: 3,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::BeforeAnyAttack,
                effect: AbilityEffect::ModifyStats {
                    health: 2,
                    attack: 0,
                    target: AbilityTarget::AllyAhead,
                },
                name: String::from("Squire's Aegis"),
                description: String::from("Give unit in front +2 health before every clash"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },

        // ==========================================
        // TIER 3 (COST 5-7): High Impact
        // ==========================================
        CardTemplate {
            template_id: "troll_brute",
            name: "Troll Brute",
            attack: 4,
            health: 5,
            play_cost: 5,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnFaint,
                effect: AbilityEffect::Damage {
                    amount: 3,
                    target: AbilityTarget::AllEnemies,
                },
                name: String::from("Death Nova"),
                description: String::from("Deal 3 damage to all enemies on death"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "lich",
            name: "Lich",
            attack: 3,
            health: 3,
            play_cost: 5,
            pitch_value: 2,
            abilities: vec![
                Ability {
                    trigger: AbilityTrigger::OnStart,
                    effect: AbilityEffect::Destroy {
                        target: AbilityTarget::AllyAhead,
                    },
                    name: String::from("Ritual"),
                    description: String::from("Sacrifice the ally in front..."),
                    condition: AbilityCondition::None,
                    max_triggers: None,
                },
                Ability {
                    trigger: AbilityTrigger::OnStart,
                    effect: AbilityEffect::SpawnUnit {
                        template_id: String::from("golem"),
                    },
                    name: String::from("...Raise Golem"),
                    description: String::from("...to spawn a 5/5 Golem"),
                    condition: AbilityCondition::None,
                    max_triggers: None,
                },
            ],
            is_token: false,
        },
        CardTemplate {
            template_id: "assassin",
            name: "Assassin",
            attack: 5,
            health: 1,
            play_cost: 5,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::Destroy {
                    target: AbilityTarget::FrontEnemy,
                },
                name: String::from("Execute"),
                description: String::from("Destroy front enemy if its health is <= 10"),
                condition: AbilityCondition::TargetHealthLessThanOrEqual { value: 10 },
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "fire_elemental",
            name: "Fire Elemental",
            attack: 4,
            health: 4,
            play_cost: 5,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::AfterUnitAttack,
                effect: AbilityEffect::Damage {
                    amount: 2,
                    target: AbilityTarget::RandomEnemy,
                },
                name: String::from("Spark"),
                description: String::from("Deal 2 damage to a random enemy after attacking"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "ogre_mauler",
            name: "Ogre Mauler",
            attack: 5,
            health: 6,
            play_cost: 6,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::ModifyStats {
                    health: 0,
                    attack: 3,
                    target: AbilityTarget::SelfUnit,
                },
                name: String::from("Crushing Blow"),
                description: String::from("Gain +3 attack at battle start"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "phoenix",
            name: "Phoenix",
            attack: 3,
            health: 3,
            play_cost: 6,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnFaint,
                effect: AbilityEffect::SpawnUnit {
                    template_id: String::from("phoenix_egg"),
                },
                name: String::from("Rebirth"),
                description: String::from("Spawn a Phoenix Egg on death"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "shield_master",
            name: "Shield Master",
            attack: 3,
            health: 10,
            play_cost: 7,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::BeforeAnyAttack,
                effect: AbilityEffect::ModifyStats {
                    health: 3,
                    attack: 0,
                    target: AbilityTarget::AllAllies,
                },
                name: String::from("Guardian's Aura"),
                description: String::from("Give ALL allies +3 health before every clash"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "void_walker",
            name: "Void Walker",
            attack: 4,
            health: 4,
            play_cost: 7,
            pitch_value: 2,
            abilities: vec![
                Ability {
                    trigger: AbilityTrigger::OnStart,
                    effect: AbilityEffect::ModifyStats {
                        health: 0,
                        attack: 2,
                        target: AbilityTarget::SelfUnit,
                    },
                    name: String::from("Leech"),
                    description: String::from("Steal 2 attack from the front enemy at start"),
                    condition: AbilityCondition::None,
                    max_triggers: None,
                },
                Ability {
                    trigger: AbilityTrigger::OnStart,
                    effect: AbilityEffect::ModifyStats {
                        health: 0,
                        attack: -2,
                        target: AbilityTarget::FrontEnemy,
                    },
                    name: String::from("Void Touch"),
                    description: String::from(" (Steal Effect Continued)"),
                    condition: AbilityCondition::None,
                    max_triggers: None,
                },
            ],
            is_token: false,
        },

        // ==========================================
        // TIER 4 (COST 8-10): Legendary
        // ==========================================
        CardTemplate {
            template_id: "mana_reaper",
            name: "Mana Reaper",
            attack: 2,
            health: 2,
            play_cost: 8,
            pitch_value: 2,
            abilities: vec![
                Ability {
                    trigger: AbilityTrigger::OnStart,
                    effect: AbilityEffect::Destroy {
                        target: AbilityTarget::HighestManaEnemy,
                    },
                    name: String::from("Harvest the Rich"),
                    description: String::from("Destroy the highest mana cost enemy"),
                    condition: AbilityCondition::None,
                    max_triggers: None,
                },
                Ability {
                    trigger: AbilityTrigger::OnStart,
                    effect: AbilityEffect::Destroy {
                        target: AbilityTarget::LowestManaEnemy,
                    },
                    name: String::from("Cull the Weak"),
                    description: String::from("Destroy the lowest mana cost enemy"),
                    condition: AbilityCondition::None,
                    max_triggers: None,
                },
            ],
            is_token: false,
        },
        CardTemplate {
            template_id: "giant_crusher",
            name: "Giant Crusher",
            attack: 6,
            health: 8,
            play_cost: 8,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::Damage {
                    amount: 4,
                    target: AbilityTarget::FrontEnemy,
                },
                name: String::from("Earthshaker"),
                description: String::from("Deal 4 damage to front enemy at start"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        CardTemplate {
            template_id: "behemoth",
            name: "Behemoth",
            attack: 10,
            health: 10,
            play_cost: 10,
            pitch_value: 2,
            abilities: vec![],
            is_token: false,
        },
        CardTemplate {
            template_id: "dragon_tyrant",
            name: "Dragon Tyrant",
            attack: 8,
            health: 12,
            play_cost: 10,
            pitch_value: 3,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::Damage {
                    amount: 3,
                    target: AbilityTarget::AllEnemies,
                },
                name: String::from("Dragon Breath"),
                description: String::from("Deal 3 damage to all enemies at start"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: false,
        },
        // ==========================================
        // TOKENS (Non-deck cards)
        // ==========================================
        CardTemplate {
            template_id: "rat_token",
            name: "Rat Token",
            attack: 1,
            health: 1,
            play_cost: 0,
            pitch_value: 0,
            abilities: vec![],
            is_token: true,
        },
        CardTemplate {
            template_id: "zombie_soldier",
            name: "Zombie Soldier",
            attack: 1,
            health: 1,
            play_cost: 1,
            pitch_value: 1,
            abilities: vec![],
            is_token: true,
        },
        CardTemplate {
            template_id: "zombie_spawn",
            name: "Zombie Spawn",
            attack: 1,
            health: 1,
            play_cost: 0,
            pitch_value: 0,
            abilities: vec![],
            is_token: true,
        },
        CardTemplate {
            template_id: "golem",
            name: "Golem",
            attack: 5,
            health: 5,
            play_cost: 0,
            pitch_value: 0,
            abilities: vec![],
            is_token: true,
        },
        CardTemplate {
            template_id: "phoenix_egg",
            name: "Phoenix Egg",
            attack: 0,
            health: 5,
            play_cost: 0,
            pitch_value: 0,
            abilities: vec![Ability {
                trigger: AbilityTrigger::OnStart,
                effect: AbilityEffect::SpawnUnit {
                    template_id: String::from("phoenix"),
                },
                name: String::from("Hatch"),
                description: String::from("Respawn the Phoenix at start of battle"),
                condition: AbilityCondition::None,
                max_triggers: None,
            }],
            is_token: true,
        },
    ]
}
