//! Unit templates and card definitions
//!
//! This module contains all unit card templates used in the game.

use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;

use crate::types::Ability;

/// Card template for creating starter deck cards
pub struct CardTemplate {
    pub template_id: &'static str,
    pub name: &'static str,
    pub attack: i32,
    pub health: i32,
    pub play_cost: i32,
    pub pitch_value: i32,
    pub abilities: Vec<Ability>,
}

/// The 10 unique unit cards for the starter deck
pub fn get_starter_templates() -> Vec<CardTemplate> {
    vec![
        CardTemplate {
            template_id: "goblin_scout",
            name: "Goblin Scout",
            attack: 1,
            health: 2,
            play_cost: 1,
            pitch_value: 2,
            abilities: vec![],
        },
        CardTemplate {
            template_id: "goblin_looter",
            name: "Goblin Looter",
            attack: 1,
            health: 1,
            play_cost: 1,
            pitch_value: 3,
            abilities: vec![],
        },
        CardTemplate {
            template_id: "militia",
            name: "Militia",
            attack: 2,
            health: 2,
            play_cost: 2,
            pitch_value: 2,
            abilities: vec![],
        },
        CardTemplate {
            template_id: "shield_bearer",
            name: "Shield Bearer",
            attack: 1,
            health: 4,
            play_cost: 2,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 2,
                    attack: 0,
                    target: crate::types::AbilityTarget::FrontAlly,
                },
                name: String::from("Shield Wall"),
                description: String::from("Heal front ally for 2"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "wolf_rider",
            name: "Wolf Rider",
            attack: 3,
            health: 2,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnFaint,
                effect: crate::types::AbilityEffect::Damage {
                    amount: 2,
                    target: crate::types::AbilityTarget::FrontEnemy,
                },
                name: String::from("Dying Bite"),
                description: String::from("Deal 2 damage to front enemy on death"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "orc_warrior",
            name: "Orc Warrior",
            attack: 3,
            health: 4,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 0,
                    attack: 2,
                    target: crate::types::AbilityTarget::SelfUnit,
                },
                name: String::from("Battle Rage"),
                description: String::from("Gain +2 attack at battle start"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "zombie_soldier",
            name: "Zombie Soldier",
            attack: 1,
            health: 1,
            play_cost: 1,
            pitch_value: 1,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnFaint,
                effect: crate::types::AbilityEffect::SpawnUnit {
                    template_id: String::from("zombie_spawn"),
                },
                name: String::from("Spawn Zombie"),
                description: String::from("Spawn a Zombie Spawn when killed"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "zombie_spawn",
            name: "Zombie Spawn",
            attack: 1,
            health: 1,
            play_cost: 0,
            pitch_value: 0,
            abilities: vec![],
        },
        CardTemplate {
            template_id: "necromancer",
            name: "Necromancer",
            attack: 2,
            health: 3,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnSpawn,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 0,
                    attack: 2,
                    target: crate::types::AbilityTarget::SelfUnit,
                },
                name: String::from("Spawn Boost"),
                description: String::from("Give +2 attack to any spawned unit"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "battle_hardened",
            name: "Battle Hardened",
            attack: 2,
            health: 3,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![
                Ability {
                    trigger: crate::types::AbilityTrigger::BeforeUnitAttack,
                    effect: crate::types::AbilityEffect::ModifyStats {
                        health: 2,
                        attack: 0,
                        target: crate::types::AbilityTarget::SelfUnit,
                    },
                    name: String::from("Pre-Battle Prep"),
                    description: String::from("Gain +2 health before each clash"),
                    condition: crate::types::AbilityCondition::default(),
                    max_triggers: None,
                },
                Ability {
                    trigger: crate::types::AbilityTrigger::AfterUnitAttack,
                    effect: crate::types::AbilityEffect::ModifyStats {
                        health: 0,
                        attack: 2,
                        target: crate::types::AbilityTarget::SelfUnit,
                    },
                    name: String::from("Adrenaline Rush"),
                    description: String::from("Gain +2 attack after each clash"),
                    condition: crate::types::AbilityCondition::default(),
                    max_triggers: None,
                },
            ],
        },
        CardTemplate {
            template_id: "troll_brute",
            name: "Troll Brute",
            attack: 4,
            health: 5,
            play_cost: 5,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnFaint,
                effect: crate::types::AbilityEffect::Damage {
                    amount: 3,
                    target: crate::types::AbilityTarget::AllEnemies,
                },
                name: String::from("Death Throes"),
                description: String::from("Deal 3 damage to all enemies on death"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "ogre_mauler",
            name: "Ogre Mauler",
            attack: 5,
            health: 6,
            play_cost: 6,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 0,
                    attack: 3,
                    target: crate::types::AbilityTarget::SelfUnit,
                },
                name: String::from("Crushing Blow"),
                description: String::from("Gain +3 attack at battle start"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "giant_crusher",
            name: "Giant Crusher",
            attack: 6,
            health: 8,
            play_cost: 8,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::Damage {
                    amount: 4,
                    target: crate::types::AbilityTarget::FrontEnemy,
                },
                name: String::from("Earthshaker"),
                description: String::from("Deal 4 damage to front enemy at battle start"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "dragon_tyrant",
            name: "Dragon Tyrant",
            attack: 8,
            health: 12,
            play_cost: 10,
            pitch_value: 3,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::Damage {
                    amount: 3,
                    target: crate::types::AbilityTarget::AllEnemies,
                },
                name: String::from("Dragon Breath"),
                description: String::from("Deal 3 damage to all enemies at battle start"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "sniper",
            name: "Sniper",
            attack: 1,
            health: 2,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::Damage {
                    amount: 2,
                    target: crate::types::AbilityTarget::FrontEnemy,
                },
                name: String::from("Headshot"),
                description: String::from("Deal 2 damage to the front enemy at battle start"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "archer",
            name: "Archer",
            attack: 1,
            health: 3,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::Damage {
                    amount: 1,
                    target: crate::types::AbilityTarget::BackEnemy,
                },
                name: String::from("Long Shot"),
                description: String::from("Deal 1 damage to the back enemy at battle start"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "goblin_grunt",
            name: "Goblin Grunt",
            attack: 2,
            health: 2,
            play_cost: 2,
            pitch_value: 1,
            abilities: vec![],
        },
        CardTemplate {
            template_id: "orc_shaman",
            name: "Orc Shaman",
            attack: 2,
            health: 3,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 2,
                    attack: 0,
                    target: crate::types::AbilityTarget::FrontAlly,
                },
                name: String::from("Healing Totem"),
                description: String::from("Heal front ally for 2 at battle start"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "troll_warrior",
            name: "Troll Warrior",
            attack: 3,
            health: 5,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![],
        },
        CardTemplate {
            template_id: "ogre_warrior",
            name: "Ogre Warrior",
            attack: 4,
            health: 6,
            play_cost: 5,
            pitch_value: 2,
            abilities: vec![],
        },
        CardTemplate {
            template_id: "zombie_captain",
            name: "Zombie Captain",
            attack: 3,
            health: 4,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![
                Ability {
                    trigger: crate::types::AbilityTrigger::OnFaint,
                    effect: crate::types::AbilityEffect::SpawnUnit {
                        template_id: String::from("zombie_soldier"),
                    },
                    name: String::from("Rally the Dead"),
                    description: String::from("Spawn a Zombie Soldier on death"),
                    condition: crate::types::AbilityCondition::default(),
                    max_triggers: None,
                },
                Ability {
                    trigger: crate::types::AbilityTrigger::OnFaint,
                    effect: crate::types::AbilityEffect::SpawnUnit {
                        template_id: String::from("zombie_soldier"),
                    },
                    name: String::from("Rally the Dead"),
                    description: String::from("Spawn a Zombie Soldier on death"),
                    condition: crate::types::AbilityCondition::default(),
                    max_triggers: None,
                },
            ],
        },
        CardTemplate {
            template_id: "corpse_cart",
            name: "Corpse Cart",
            attack: 0,
            health: 4,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnAllyFaint,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 0,
                    attack: 2,
                    target: crate::types::AbilityTarget::SelfUnit,
                },
                name: String::from("Scavenge"),
                description: String::from("Gain +2 attack when an ally faints"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "lich",
            name: "Lich",
            attack: 3,
            health: 3,
            play_cost: 5,
            pitch_value: 2,
            abilities: vec![
                Ability {
                    trigger: crate::types::AbilityTrigger::OnStart,
                    effect: crate::types::AbilityEffect::Destroy {
                        target: crate::types::AbilityTarget::AllyAhead,
                    },
                    name: String::from("Ritual Sacrifice"),
                    description: String::from("Kill the ally in front"),
                    condition: crate::types::AbilityCondition::default(),
                    max_triggers: None,
                },
                Ability {
                    trigger: crate::types::AbilityTrigger::OnStart,
                    effect: crate::types::AbilityEffect::SpawnUnit {
                        template_id: String::from("golem"),
                    },
                    name: String::from("Raise Golem"),
                    description: String::from("Spawn a 5/5 Golem"),
                    condition: crate::types::AbilityCondition::default(),
                    max_triggers: None,
                },
            ],
        },
        CardTemplate {
            template_id: "golem",
            name: "Golem",
            attack: 5,
            health: 5,
            play_cost: 0,
            pitch_value: 0,
            abilities: vec![],
        },
        CardTemplate {
            template_id: "raging_orc",
            name: "Raging Orc",
            attack: 2,
            health: 8,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnDamageTaken,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 0,
                    attack: 2,
                    target: crate::types::AbilityTarget::SelfUnit,
                },
                name: String::from("Berserk"),
                description: String::from("Gain +2 attack when hurt"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "zombie_breeder",
            name: "Zombie Breeder",
            attack: 2,
            health: 4,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnDamageTaken,
                effect: crate::types::AbilityEffect::SpawnUnit {
                    template_id: String::from("zombie_spawn"),
                },
                name: String::from("Undead Horde"),
                description: String::from("Spawn a Zombie Spawn when hurt"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: Some(2),
            }],
        },
        CardTemplate {
            template_id: "pain_smith",
            name: "Pain Smith",
            attack: 3,
            health: 3,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![
                Ability {
                    trigger: crate::types::AbilityTrigger::OnStart,
                    effect: crate::types::AbilityEffect::ModifyStats {
                        health: 0,
                        attack: 2,
                        target: crate::types::AbilityTarget::AllAllies,
                    },
                    name: String::from("Sharpen Blades"),
                    description: String::from("Give all allies +2 attack"),
                    condition: crate::types::AbilityCondition::default(),
                    max_triggers: None,
                },
                Ability {
                    trigger: crate::types::AbilityTrigger::OnStart,
                    effect: crate::types::AbilityEffect::Damage {
                        amount: 1,
                        target: crate::types::AbilityTarget::AllAllies,
                    },
                    name: String::from("Forged in Fire"),
                    description: String::from("Deal 1 damage to all allies"),
                    condition: crate::types::AbilityCondition::default(),
                    max_triggers: None,
                },
            ],
        },
        CardTemplate {
            template_id: "headhunter",
            name: "Headhunter",
            attack: 4,
            health: 2,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::Damage {
                    amount: 5,
                    target: crate::types::AbilityTarget::LowestHealthEnemy,
                },
                name: String::from("Assassinate"),
                description: String::from("Deal 5 damage to the enemy with the lowest health"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "giant_slayer",
            name: "Giant Slayer",
            attack: 2,
            health: 2,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::Damage {
                    amount: 3,
                    target: crate::types::AbilityTarget::HighestAttackEnemy,
                },
                name: String::from("Take Down"),
                description: String::from("Deal 3 damage to the enemy with the highest attack"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        CardTemplate {
            template_id: "behemoth",
            name: "Behemoth",
            attack: 10,
            health: 10,
            play_cost: 10,
            pitch_value: 2,
            abilities: vec![],
        },
        CardTemplate {
            template_id: "mana_reaper",
            name: "Mana Reaper",
            attack: 2,
            health: 2,
            play_cost: 8,
            pitch_value: 2,
            abilities: vec![
                Ability {
                    trigger: crate::types::AbilityTrigger::OnStart,
                    effect: crate::types::AbilityEffect::Destroy {
                        target: crate::types::AbilityTarget::HighestManaEnemy,
                    },
                    name: String::from("Harvest the Rich"),
                    description: String::from("Destroy the highest mana cost enemy"),
                    condition: crate::types::AbilityCondition::default(),
                    max_triggers: None,
                },
                Ability {
                    trigger: crate::types::AbilityTrigger::OnStart,
                    effect: crate::types::AbilityEffect::Destroy {
                        target: crate::types::AbilityTarget::LowestManaEnemy,
                    },
                    name: String::from("Cull the Weak"),
                    description: String::from("Destroy the lowest mana cost enemy"),
                    condition: crate::types::AbilityCondition::default(),
                    max_triggers: None,
                },
            ],
        },
        CardTemplate {
            template_id: "shield_squire",
            name: "Shield Squire",
            attack: 2,
            health: 3,
            play_cost: 4,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::BeforeAnyAttack,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 2,
                    attack: 0,
                    target: crate::types::AbilityTarget::AllyAhead,
                },
                name: String::from("Squire's Shield"),
                description: String::from("Give the unit in front +2 Health before every clash"),
                condition: crate::types::AbilityCondition::default(),
                max_triggers: None,
            }],
        },
        // Example unit demonstrating conditional abilities
        CardTemplate {
            template_id: "nurse_goblin",
            name: "Nurse Goblin",
            attack: 1,
            health: 3,
            play_cost: 2,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::BeforeAnyAttack,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 2,
                    attack: 0,
                    target: crate::types::AbilityTarget::AllyAhead,
                },
                name: String::from("Emergency Heal"),
                description: String::from("Give the unit in front +2 Health if its health is 6 or less"),
                condition: crate::types::AbilityCondition::TargetHealthLessThanOrEqual { value: 6 },
                max_triggers: None,
            }],
        },
        // Example unit demonstrating "Last Stand" conditional (only activates when alone)
        CardTemplate {
            template_id: "lone_wolf",
            name: "Lone Wolf",
            attack: 2,
            health: 4,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::BeforeUnitAttack,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 0,
                    attack: 5,
                    target: crate::types::AbilityTarget::SelfUnit,
                },
                name: String::from("Last Stand"),
                description: String::from("Gain +5 attack if you are the only ally"),
                condition: crate::types::AbilityCondition::AllyCountAtMost { count: 1 },
                max_triggers: None,
            }],
        },
        // Example unit demonstrating "Swarm" conditional (activates with many allies)
        CardTemplate {
            template_id: "pack_leader",
            name: "Pack Leader",
            attack: 2,
            health: 3,
            play_cost: 3,
            pitch_value: 2,
            abilities: vec![Ability {
                trigger: crate::types::AbilityTrigger::OnStart,
                effect: crate::types::AbilityEffect::ModifyStats {
                    health: 1,
                    attack: 1,
                    target: crate::types::AbilityTarget::AllAllies,
                },
                name: String::from("Pack Tactics"),
                description: String::from("Give all allies +1/+1 if you have 3 or more allies"),
                condition: crate::types::AbilityCondition::AllyCountAtLeast { count: 3 },
                max_triggers: None,
            }],
        },
    ]
}
